# Generated by Django 5.2.13 on 2026-04-24 04:57

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import F


def forwards_order_state(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    OrderItem = apps.get_model('orders', 'OrderItem')
    Order.objects.filter(subtotal_price=0).update(subtotal_price=F('total_price'))
    Order.objects.filter(status='pending').update(status='pending_payment')
    Order.objects.filter(status='confirmed').update(status='paid')
    OrderItem.objects.filter(original_unit_price=0).update(original_unit_price=F('unit_price'))


def backwards_order_state(apps, schema_editor):
    Order = apps.get_model('orders', 'Order')
    Order.objects.filter(status='pending_payment').update(status='pending')
    Order.objects.filter(status='cart').update(status='pending')
    Order.objects.filter(status='paid').update(status='confirmed')
    Order.objects.filter(status='refunded').update(status='cancelled')


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        ('products', '0003_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='order',
            name='discount_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='refunded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='reservation_expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='original_unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RunPython(forwards_order_state, backwards_order_state),
        migrations.AlterField(
            model_name='order',
            name='shipping_country',
            field=models.CharField(default='Bangladesh', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('cart', 'Cart'), ('pending_payment', 'Pending Payment'), ('paid', 'Paid'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='cart', max_length=20),
        ),
        migrations.CreateModel(
            name='StockReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('converted', 'Converted to Sale'), ('released', 'Released')], db_index=True, default='active', max_length=20)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('reason', models.CharField(blank=True, max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('converted_at', models.DateTimeField(blank=True, null=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_reservations', to='products.product')),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'expires_at'], name='orders_stoc_status_e8aa04_idx'), models.Index(fields=['order', 'status'], name='orders_stoc_order_i_a4ab61_idx')],
            },
        ),
    ]
