# Generated by Django 5.2.12 on 2026-04-04 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category_rank',
            field=models.IntegerField(default=0, help_text="Rank within the product's category (0 = unranked)"),
        ),
        migrations.AddField(
            model_name='product',
            name='category_rank_display',
            field=models.CharField(blank=True, help_text="Human-readable rank label, e.g. '#2 in Gaming'", max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='sold_recently',
            field=models.IntegerField(default=0, help_text='Number of units sold recently (shown on card)'),
        ),
    ]
