# Generated by Django 5.2.13 on 2026-04-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_enable_pg_trgm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='get_in',
            field=models.CharField(blank=True, help_text='Delivery promise text', max_length=300, verbose_name='GET IN'),
        ),
        migrations.AlterField(
            model_name='product',
            name='get_in_bn',
            field=models.CharField(blank=True, help_text='Bengali delivery promise text', max_length=300, verbose_name='GET IN BN'),
        ),
    ]
