# Generated by Django 5.2.13 on 2026-04-24 04:57

import django.db.models.deletion
from django.db import migrations, models


def forwards_offer_scope(apps, schema_editor):
    PricelistOffer = apps.get_model('offers', 'PricelistOffer')
    PricelistOffer.objects.filter(product__isnull=False).update(scope='product')
    PricelistOffer.objects.filter(product__isnull=True, category__isnull=False).update(scope='category')
    PricelistOffer.objects.filter(product__isnull=True, category__isnull=True).update(scope='cart')


def backwards_offer_scope(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('offers', '0001_initial'),
        ('products', '0003_product_brand'),
        ('sellers', '0002_sellerpayout'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pricelistoffer',
            options={'ordering': ['priority', '-created_at']},
        ),
        migrations.AddField(
            model_name='pricelistoffer',
            name='campaign_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='pricelistoffer',
            name='coupon_code',
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AddField(
            model_name='pricelistoffer',
            name='max_discount_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='pricelistoffer',
            name='min_order_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='pricelistoffer',
            name='priority',
            field=models.IntegerField(default=100, help_text='Lower numbers win ties'),
        ),
        migrations.AddField(
            model_name='pricelistoffer',
            name='scope',
            field=models.CharField(choices=[('product', 'Product'), ('category', 'Category'), ('seller', 'Seller'), ('cart', 'Cart')], db_index=True, default='product', max_length=20),
        ),
        migrations.AddField(
            model_name='pricelistoffer',
            name='seller',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='sellers.seller'),
        ),
        migrations.RunPython(forwards_offer_scope, backwards_offer_scope),
        migrations.AlterField(
            model_name='pricelistoffer',
            name='discount_type',
            field=models.CharField(choices=[('fixed', 'Fixed Amount'), ('percent', 'Percentage')], default='percent', max_length=20),
        ),
        migrations.AlterField(
            model_name='pricelistoffer',
            name='min_qty',
            field=models.IntegerField(default=1, help_text='Minimum quantity to activate'),
        ),
        migrations.AddIndex(
            model_name='pricelistoffer',
            index=models.Index(fields=['scope', 'is_active'], name='offers_pric_scope_09ac85_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelistoffer',
            index=models.Index(fields=['coupon_code', 'is_active'], name='offers_pric_coupon__235145_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelistoffer',
            index=models.Index(fields=['valid_from', 'valid_to'], name='offers_pric_valid_f_66b5db_idx'),
        ),
    ]
