# Generated by Django 5.2.12 on 2026-03-30 05:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tran_id', models.CharField(default=uuid.uuid4, help_text='Our unique transaction ID sent to SSLCommerz', max_length=128, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='BDT', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('gateway', models.CharField(default='sslcommerz', max_length=50)),
                ('val_id', models.CharField(blank=True, help_text='SSLCommerz validation ID', max_length=128)),
                ('bank_tran_id', models.CharField(blank=True, max_length=128)),
                ('card_type', models.CharField(blank=True, help_text='bKash / Nagad / VISA / etc.', max_length=64)),
                ('store_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('risk_level', models.CharField(blank=True, max_length=10)),
                ('raw_response', models.JSONField(blank=True, default=dict, help_text='Full IPN payload for audit')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
