# Generated by Django 5.2.13 on 2026-04-24 04:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymenttransaction',
            name='callback_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, db_index=True, max_length=128),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='last_callback_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='paid_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymenttransaction',
            name='processed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gateway', models.CharField(default='sslcommerz', max_length=50)),
                ('tran_id', models.CharField(db_index=True, max_length=128)),
                ('event_key', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=40)),
                ('gateway_status', models.CharField(blank=True, max_length=40)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('duplicate', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='payments.paymenttransaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tran_id', 'event_type'], name='payments_pa_tran_id_fc4efc_idx'), models.Index(fields=['processed', 'created_at'], name='payments_pa_process_662701_idx')],
            },
        ),
    ]
